### ISSUE TITLE
Improve Login Page CSS 

### ISSUE THREAD

**Issue by akash205sharma** [akash205sharma/ShopEasy#1]
The Styling of my Login page is Not Smooth and attractive.

**Comment by anandshukla15** [comment]
@akash205sharma  please assign to me

**Comment by ADARSHsri2004** [comment]
@akash205sharma assign this to me

**Comment by mariontamnai** [comment]
Can I help here

**Comment by akash205sharma** [comment]
@mariontamnai yes you can try and send photo of your work

**Comment by mariontamnai** [comment]
Thanks when I am done, I'll let you know

**Comment by mariontamnai** [comment]
hi ill be done by tomorrow just fixing some small issues

**Comment by mariontamnai** [comment]
[image: Screenshot 2024-11-03 at 15.13.30.png]
                                     Sorry for not getting back to you
sooner, but you can take a look at it. Also, it has hover effects, which
I can not display on the screenshot😅
