### ISSUE TITLE
Make ShopEasy Responsive

### ISSUE THREAD

**Issue by akash205sharma** [akash205sharma/ShopEasy#3]
ShopEasy Is Not Responsive at all. Make it Responsive and Improve its Alignment .
It Should be feasible For Android and Tablets both

**Comment by olorunfemisamuel** [comment]
Can I work on this??

**Comment by akash205sharma** [comment]
@olorunfemisamuel  Yes you can.

**Comment by akash205sharma** [comment]
@olorunfemisamuel i have assigned this to you

**Comment by Jeevan-Neupane** [comment]
Hey are you working in this
I want to work  in it

**Comment by olorunfemisamuel** [comment]
Yes, I am working on it.

**Comment by akash205sharma** [comment]
@olorunfemisamuel Can You complete this early

**Comment by olorunfemisamuel** [comment]
Yes, I can. Just having some serious errors anytime I try to run the code on my machine. But I am working on it.

**Comment by olorunfemisamuel** [comment]
I am done with it.
